/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package termProject;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTINITBLOCK = 1;
  public int JJTDECLARATION = 2;
  public int JJTINTEGERSECT = 3;
  public int JJTFLOATSECT = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTINITIALIZATION = 6;
  public int JJTCONSTANT = 7;
  public int JJTCODEBLOCK = 8;
  public int JJTSWITCHSECT = 9;
  public int JJTSWITCHBODY = 10;
  public int JJTDEFAULTSECT = 11;
  public int JJTCASESECT = 12;
  public int JJTCONDSTATEMENT = 13;
  public int JJTCONDOP = 14;
  public int JJTASSIGNMENTSTATEMENT = 15;
  public int JJTLHS = 16;
  public int JJTRHS = 17;
  public int JJTADDITIONOPERATION = 18;
  public int JJTINTERMEDIATEADDITION = 19;
  public int JJTMULTIPLICATIONOPERATION = 20;
  public int JJTINTERMEDIATEMULTIPLICATION = 21;
  public int JJTIDENTCONS = 22;
  public int JJTOUTPUTSECT = 23;
  public int JJTFORSECT = 24;
  public int JJTFORBODY = 25;
  public int JJTDECLARE = 26;
  public int JJTINDEOPERATION = 27;
  public int JJTINDEOPERATOR = 28;


  public String[] jjtNodeName = {
    "Start",
    "initBlock",
    "declaration",
    "integerSect",
    "floatSect",
    "identifier",
    "initialization",
    "constant",
    "codeBlock",
    "switchSect",
    "switchBody",
    "defaultSect",
    "caseSect",
    "condStatement",
    "condOp",
    "assignmentStatement",
    "LHS",
    "RHS",
    "additionOperation",
    "intermediateAddition",
    "multiplicationOperation",
    "intermediateMultiplication",
    "identCons",
    "outputSect",
    "forSect",
    "forBody",
    "declare",
    "InDeOperation",
    "InDeOperator",
  };
}
/* JavaCC - OriginalChecksum=8412671f8951078d921a0d83dda80ecd (do not edit this line) */
