/* Generated By:JJTree&JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package termProject;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int SWITCH = 9;
  /** RegularExpression Id. */
  int CASE = 10;
  /** RegularExpression Id. */
  int DEFALT = 11;
  /** RegularExpression Id. */
  int OUTPUT = 12;
  /** RegularExpression Id. */
  int FORLOOP = 13;
  /** RegularExpression Id. */
  int ENDLOOP = 14;
  /** RegularExpression Id. */
  int STPRO = 15;
  /** RegularExpression Id. */
  int EDPRO = 16;
  /** RegularExpression Id. */
  int INITBLOCK = 17;
  /** RegularExpression Id. */
  int CODEBLOCK = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MUL = 21;
  /** RegularExpression Id. */
  int MINUS = 22;
  /** RegularExpression Id. */
  int DIVIDE = 23;
  /** RegularExpression Id. */
  int GE = 24;
  /** RegularExpression Id. */
  int LE = 25;
  /** RegularExpression Id. */
  int EQ = 26;
  /** RegularExpression Id. */
  int LT = 27;
  /** RegularExpression Id. */
  int GT = 28;
  /** RegularExpression Id. */
  int ASSIGN = 29;
  /** RegularExpression Id. */
  int SEMICOLON = 30;
  /** RegularExpression Id. */
  int COLON = 31;
  /** RegularExpression Id. */
  int INCREAMENT = 32;
  /** RegularExpression Id. */
  int DECREAMENT = 33;
  /** RegularExpression Id. */
  int IDENTIFIER = 34;
  /** RegularExpression Id. */
  int DECIMAL = 35;
  /** RegularExpression Id. */
  int INTEGER = 36;
  /** RegularExpression Id. */
  int STRING = 37;
  /** RegularExpression Id. */
  int QUOTE = 38;
  /** RegularExpression Id. */
  int LETTER = 39;
  /** RegularExpression Id. */
  int LETTER1 = 40;
  /** RegularExpression Id. */
  int DIGIT = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"int\"",
    "\"float\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"output\"",
    "\"forLoop\"",
    "\"endLoop\"",
    "\"StartProgram\"",
    "\"EndProgram\"",
    "\"InitBlock:\"",
    "\"CodeBlock:\"",
    "\",\"",
    "\"+\"",
    "\"*\"",
    "\"-\"",
    "\"/\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\";\"",
    "\":\"",
    "\"++\"",
    "\"--\"",
    "<IDENTIFIER>",
    "<DECIMAL>",
    "<INTEGER>",
    "<STRING>",
    "\"\\\"\"",
    "<LETTER>",
    "<LETTER1>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
  };

}
